export const ActionTypes = {
    SET_BRANDS: "SET_BRANDS",
    SET_SIZES: "SET_SIZES",
    SET_DISCOUNTS: "SET_DISCOUNTS",
    SET_SEASONS: "SET_SEASONS",
    SET_COLORS: "SET_COLORS",
    SET_GENDERS: "SET_GENDERS",
    SET_CATEGORY: "SET_CATEGORY",
    SEARCH_VAL: "SEARCH_VAL",
    GENDER_VAL: "GENDER_VAL",
    GET_BRANDS: "GET_BRANDS",
}